sharinpix/src/objects/EinsteinDataset__c.object
<CustomObject>
    <fields>
        <fullName>EinsteinVisionProject__c</fullName>
        <label>Einstein Vision Project</label>
        <referenceTo>EinsteinVisionProject__c</referenceTo>
        <relationshipLabel>Einstein Vision Datasets</relationshipLabel>
        <relationshipName>Einstein_Vision_Datasets_2</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <label>Einstein Dataset</label>
    <nameField>
        <label>Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Einstein Datasets</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

sharinpix/src/objects/EinsteinLabel__c.object
<CustomObject>
    <fields>
        <fullName>EinsteinVisionProject__c</fullName>
        <label>Einstein Vision Project</label>
        <referenceTo>EinsteinVisionProject__c</referenceTo>
        <relationshipLabel>Einstein Vision Labels</relationshipLabel>
        <relationshipName>Einstein_Vision_Projects</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <label>Einstein Label</label>
    <nameField>
        <label>Label Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Einstein Labels</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

sharinpix/src/objects/EinsteinModel__c.object
<CustomObject>
    <fields>
        <fullName>EinsteinDataset__c</fullName>
        <label>Einstein Dataset</label>
        <referenceTo>EinsteinDataset__c</referenceTo>
        <relationshipLabel>Einstein Models</relationshipLabel>
        <relationshipName>Einstein_Models</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>Epochs__c</fullName>
        <description>Optional. Number of training iterations for the neural network. Valid values are 1–100. If not specified, the default is calculated based on the dataset size. The larger the number, the longer the training takes to complete.</description>
        <inlineHelpText>Optional. Number of training iterations for the neural network. Valid values are 1–100. If not specified, the default is calculated based on the dataset size. The larger the number, the longer the training takes to complete.</inlineHelpText>
        <label>Epochs</label>
        <precision>3</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>LearningRate__c</fullName>
        <description>Optional. Specifies how much the gradient affects the optimization of the model at each time step. Use this parameter to tune your model. Valid values are between 0.0001 and 0.01. If not specified, the default is 0.0001. We recommend keeping this value between 0.0001 and 0.001.</description>
        <inlineHelpText>Optional. Specifies how much the gradient affects the optimization of the model at each time step. Use this parameter to tune your model. Valid values are between 0.0001 and 0.01. If not specified, the default is 0.0001.</inlineHelpText>
        <label>LearningRate</label>
        <precision>8</precision>
        <scale>6</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>TrainParams__c</fullName>
        <description>Optional. JSON that contains parameters that specify how the model is created. Valid values:
{&quot;trainSplitRatio&quot;: 0.n}—Lets you specify the ratio of data used to train the dataset and the data used to test the model. The default split ratio is 0.9; 90% of the data is used to train the dataset and create the model and 10% of the data is used to test the model. If you pass in a split ratio of 0.6, then 60% of the data is used to train the dataset and create the model and 40% of the data is used to test the model.</description>
        <inlineHelpText>Optional. JSON that contains parameters that specify how the model is created. Valid values:
{&quot;trainSplitRatio&quot;: 0.n}—Lets you specify the ratio of data used to train the dataset and the data used to test the model.</inlineHelpText>
        <label>TrainParams</label>
        <length>131072</length>
        <type>LongTextArea</type>
    </fields>
    <label>Einstein Model</label>
    <nameField>
        <label>Model Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Einstein Models</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

sharinpix/src/objects/EinsteinVisionProject__c.object
<CustomObject>
    <label>Einstein Vision Project</label>
    <nameField>
        <label>Project Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Einstein Vision Projects</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

sharinpix/src/classes/EinsteinTriggerUtils.cls
/**
 * Class for Einstein triggers
 * @author Kevan
 * @since April 2017
 */
public with sharing class EinsteinTriggerUtils {
    /**
     * Call SharinPix api to create dataset
     * @param datasetId Salesforce id of the dataset
     */
    @future(callout=true)
    public static void createSharinPixDataset(Id datasetId){
        EinsteinDataset__c dataset = [select id, name, EinsteinVisionProject__c from EinsteinDataset__c where id = :String.escapeSingleQuotes(datasetId)];
        list<EinsteinLabel__c> einsteinLabels = [select id, name from EinsteinLabel__c where EinsteinVisionProject__c = :String.escapeSingleQuotes(dataset.EinsteinVisionProject__c)];
        list<string> labels = new list<string>();
        for(EinsteinLabel__c label: einsteinLabels){
            labels.add(label.name);
        }
        map<string, string> payload = new map<string, string>{
            'name' => dataset.name,
            'sfid' => dataset.Id,
            'labels' => String.join(labels, ','),
            'albumId' => dataset.EinsteinVisionProject__c
        };
        Client clientInstance = Client.getInstance();
        object response = clientInstance.post('/einstein_dataset', Blob.valueof(JSON.serialize(payload)), new map<string, object>{'einstein'=>true});
    }

    /**
     * Call SharinPix api to create model
     * @param modelId Salesforce id of the model
     */
    @future(callout=true)
    public static void createSharinPixModel(id modelId){
        EinsteinModel__c model = [select Id, Name, Epochs__c, TrainParams__c, LearningRate__c, EinsteinDataset__c from EinsteinModel__c where Id = :modelId];
        map<string, object> payload = new map<string, object>{
            'name' => model.name,
            'sfid' => model.Id,
            'epochs' => model.Epochs__c,
            'learningRate' => model.LearningRate__c,
            'trainParams' => model.TrainParams__c,
            'datasetSfid' => model.EinsteinDataset__c
        };
        Client clientInstance = Client.getInstance();
        object response = clientInstance.post('/einstein_model', Blob.valueof(JSON.serialize(payload)), new map<string, object>{'einstein'=>true});
    }
}