sharinpix/src/objects/EinsteinDataset__c.object
<CustomObject>
    <fields>
        <fullName>EinsteinVisionProject__c</fullName>
        <label>Einstein Vision Project</label>
        <referenceTo>EinsteinVisionProject__c</referenceTo>
        <relationshipLabel>Einstein Vision Datasets</relationshipLabel>
        <relationshipName>Einstein_Vision_Datasets_2</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <label>Einstein Dataset</label>
    <nameField>
        <label>Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Einstein Datasets</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

sharinpix/src/objects/EinsteinLabel__c.object
<CustomObject>
    <fields>
        <fullName>EinsteinVisionProject__c</fullName>
        <label>Einstein Vision Project</label>
        <referenceTo>EinsteinVisionProject__c</referenceTo>
        <relationshipLabel>Einstein Vision Labels</relationshipLabel>
        <relationshipName>Einstein_Vision_Projects</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <label>Einstein Label</label>
    <nameField>
        <label>Label Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Einstein Labels</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

sharinpix/src/objects/EinsteinVisionProject__c.object
<CustomObject>
    <label>Einstein Vision Project</label>
    <nameField>
        <label>Project Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Einstein Vision Projects</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

sharinpix/src/classes/EinsteinDatasetControllerTest.cls
@isTest
private class EinsteinDatasetControllerTest {

    static String API_URL = 'https://api.sharinpix.com/api/v1';
    private static EinsteinVisionProject__c project;
    private static list<EinsteinLabel__c> labels;
    private static EinsteinDataset__c dataset;

    static {
        project = new EinsteinVisionProject__c(Name='project');
        insert project;

        labels = new list<EinsteinLabel__c>{
            new EinsteinLabel__c(Name='red', EinsteinVisionProject__c=project.id),
            new EinsteinLabel__c(Name='blue', EinsteinVisionProject__c=project.id),
            new EinsteinLabel__c(Name='yellow', EinsteinVisionProject__c=project.id)
        };
        insert labels;

        dataset = new EinsteinDataset__c(Name='Dataset', EinsteinVisionProject__c=project.id);
        insert dataset;
    }

	@isTest static void displayAlbumTest() {
        Map<String, HttpCalloutMock> requestResponses = new Map<String, HttpCalloutMock> {
            API_URL + '/einstein_dataset' => new SingleRequestMock(200, 'OK', '{"dataset_id": "IEHOUPWMCEROEH9823NC"}', null),
            API_URL + '/einstein_model' => new SingleRequestMock(200, 'OK', '{"model_id": "IEHOUPWMCEROEH9823NC"}', null)
        };
        Test.setMock(HttpCalloutMock.class, new MultiRequestMock(requestResponses));

        ApexPages.StandardController stdController;
        PageReference pageRef = Page.EinsteinDataset;

        Test.startTest();
        stdController = new ApexPages.StandardController(dataset);
        pageRef.getParameters().put('id', String.valueOf(dataset.Id));
        Test.setCurrentPage(pageRef);
        EinsteinDatasetController controller = new EinsteinDatasetController(stdController);
        Test.stopTest();

        string url = Client.getInstance().getHost() +'/pagelayout/' +dataset.Id +'?token=';

        system.assert(controller.albumUrl.startsWith(url));
	}
}